name: Publish Docker image in testing

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  push_to_registry:
    name: Push Docker image to Yandex Container Registry
    runs-on: ubuntu-latest
    environment:
      name: testing
      url: ${{vars.URL}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Yandex Container Registry
        id: auth
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.DOCKER_OAUTH }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{vars.DOCKER_NAME }}:${{ vars.TAG }}
