name: 'Yandex Cloud test workflow'

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  init-yc:
    name: 'Initialize YC CLI'
    runs-on: ubuntu-latest
    steps:
      - name: Install YC CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yc -n
          echo ":/opt/yc/bin" >> $GITHUB_PATH
      - name: Create profile YC CLI
        run: |
          yc config profile create github-actions
          yc config set cloud-id ${{ vars.YC_CLOUD_ID }}
          yc config set folder-id ${{ vars.YC_FOLDER_ID }}
          echo '${{ secrets.YC_SERVICE_ACCOUNT_KEY }}' > key.json
          yc config set service-account-key key.json
      - run: yc serverless container list
