name: 'Yandex Cloud test workflow'

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  init-yc:
    name: 'Initialize YC CLI'
    runs-on: ubuntu-latest
    steps:
      - name: Install YC CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yc -n
          echo ":/opt/yc/bin" >> $GITHUB_PATH
      - name: Create profile YC CLI
        run: yc config profile create github-actions-profile
      - run: yc config list
