name: 'Yandex Cloud test workflow'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  init-yc:
    name: 'Initialize YC CLI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
